# ==========================
# Application
# ==========================
spring.application.name=QuantityMeasurementApp

# ==========================
# H2 Database
# ==========================
spring.datasource.url=jdbc:h2:./quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================
# JPA
# ==========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# H2 Console
# ==========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================
# Logging
# ==========================
logging.level.root=INFO
logging.level.org.example=DEBUG
logging.level.org.springframework.web=INFO

# ==========================
# Jackson
# ==========================
spring.jackson.serialization.indent-output=true
# ==============================
# Google OAuth2 Client Configuration
# ===========================

# ==============================
# JWT Configuration
# ==============================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}



# ==============================
# Security - Public Endpoints
# ==============================
app.security.public-paths=/api/auth/**,/swagger-ui/**,/api-docs/**,/actuator/health